In [2]:
# !pip install numpy

In [3]:
import numpy as np

In [4]:
lista = [1, 2, 3, 4, 5]

In [5]:
tablica = np.array(lista)

In [6]:
tablica

array([1, 2, 3, 4, 5])

In [12]:
np.array([[1, 2, 4], [1, 2, 3]])

array([[1, 2, 4],
       [1, 2, 3]])

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(4, 4)

array([[0.70680399, 0.87296897, 0.5462171 , 0.59952395],
       [0.43157583, 0.97357212, 0.03982856, 0.36696778],
       [0.4068421 , 0.93606806, 0.84296334, 0.00305393],
       [0.30765597, 0.11454524, 0.55460451, 0.40985677]])

# operacje

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [21]:
a + b

array([5, 7, 9])

In [22]:
a - b

array([-3, -3, -3])

In [23]:
a * b

array([ 4, 10, 18])

In [24]:
a * 5

array([ 5, 10, 15])

# funkcje

In [25]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [26]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [27]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

# indeksowanie

In [28]:
a[0]

np.int64(1)

In [30]:
a.dtype

dtype('int64')

In [31]:
a[0:2]

array([1, 2])

In [33]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [34]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:

c[1][1:]

array([5, 6])

In [39]:
c[1,1:]

array([5, 6])

In [43]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [45]:
b = np.array([[5, 6]])
b.T

array([[5],
       [6]])

In [47]:
x = np.concatenate((a, b.T), axis=1)

In [48]:
print(x)

[[1 2 5]
 [3 4 6]]


In [49]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 9]])

np.dot(A, B)

array([[19, 24],
       [43, 54]])

In [50]:
A.dot(B)

array([[19, 24],
       [43, 54]])

In [51]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [52]:
A

array([[1, 2],
       [3, 4]])

In [53]:
b = np.array([1, 2])

In [54]:
np.linalg.solve(A, b)

array([0. , 0.5])

In [55]:
b

array([1, 2])

In [56]:
np.mean(b)

np.float64(1.5)

In [57]:
np.mean(A)

np.float64(2.5)

In [58]:
lista  = [1, 2, 3, 4, 5] * 1000000

In [60]:
%timeit sum(lista)

36.1 ms ± 2.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [61]:
np_list = np.array(lista)

In [63]:
%timeit np_list.sum()

5.74 ms ± 411 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [64]:
%timeit [x ** 3 for x in lista]

662 ms ± 47.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [65]:
%timeit np_list ** 3

37.3 ms ± 6.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [66]:
x = np_list

In [67]:
id(x)

1786112522544

In [68]:
id(np_list)

1786112522544