# Wprowadzenie do NumPy

## 1. Czym jest NumPy?

NumPy (Numerical Python) to biblioteka Pythona służąca do obsługi dużych, wielowymiarowych tablic i macierzy, wraz z bogatym zestawem funkcji matematycznych do ich przetwarzania. Jest fundamentem dla wielu innych bibliotek naukowych w Pythonie, takich jak SciPy, Pandas czy Matplotlib.

## 2. Instalacja NumPy

Aby zainstalować NumPy, możesz użyć pip:

```bash
pip install numpy
```

Jeśli używasz Anacondy:

```bash
conda install numpy
```

## 3. Podstawy pracy z NumPy

### 3.1. Importowanie biblioteki

Standardowo NumPy importuje się jako `np`:

In [2]:
import numpy as np

### 3.2. Tworzenie tablic

- **Z listy Pythona:**

In [4]:
lista = [1, 2, 3, 4, 5]
tablica = np.array(lista)
tablica

array([1, 2, 3, 4, 5])

- **Tablice wielowymiarowe:**

In [6]:
macierz = np.array([[1, 2, 3], [4, 5, 6]])
macierz

array([[1, 2, 3],
       [4, 5, 6]])

### 3.3. Generowanie tablic

- **Tablica wypełniona zerami:**

In [7]:
zera = np.zeros((3, 4))
zera

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- **Tablica wypełniona jedynkami:**

In [8]:
jedynki = np.ones((2, 5))
jedynki

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- **Tablica z losowymi liczbami:**

In [9]:
losowe = np.random.rand(4, 4)
losowe

array([[0.81454706, 0.1093199 , 0.82448624, 0.60892021],
       [0.06184484, 0.64772729, 0.38148796, 0.23405545],
       [0.95701954, 0.20414634, 0.32102295, 0.50202946],
       [0.71195613, 0.46528044, 0.70622112, 0.70573311]])

- **Tablica z określonym zakresem liczb:**

In [10]:
zakres = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]


### 3.4. Podstawowe operacje na tablicach

- **Operacje arytmetyczne:**

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [13]:
a + b          # [5, 7, 9]

array([5, 7, 9])

In [14]:
a - b        # [-3, -3, -3]

array([-3, -3, -3])

In [15]:
a * b           # [4, 10, 18]

array([ 4, 10, 18])

In [16]:
a / b          # [0.25, 0.4, 0.5]

array([0.25, 0.4 , 0.5 ])

- **Funkcje matematyczne:**

In [17]:
sinusy = np.sin(a)
sinusy

array([0.84147098, 0.90929743, 0.14112001])

In [18]:
logarytmy = np.log(a)
logarytmy

array([0.        , 0.69314718, 1.09861229])

In [19]:
pierwiastki = np.sqrt(a)
pierwiastki

array([1.        , 1.41421356, 1.73205081])

### 3.5. Indeksowanie i cięcie tablic

- **Indeksowanie:**

In [20]:
element = a[0]  # 1
element

1

- **Cięcie:**

In [21]:
podtablica = a[0:2]  # [1, 2]
podtablica

array([1, 2])

- **Indeksowanie wielowymiarowe:**

In [23]:
element = macierz[0, 1]  # 2
element

2

### 3.6. Kształt i rozmiar tablic

- **Sprawdzanie kształtu:**

In [24]:

macierz.shape  # (2, 3)

(2, 3)

- **Zmiana kształtu:**

In [26]:
macierz.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

- **Rozmiar tablicy:**

In [28]:
macierz.size  # 6


6

### 3.7. Łączenie i dzielenie tablic

- **Łączenie:**

In [29]:
połączone = np.concatenate((a, b))  # [1, 2, 3, 4, 5, 6]
połączone

array([1, 2, 3, 4, 5, 6])

- **Dzielenie:**

In [30]:
podzielone = np.split(a, 3)  # [array([1]), array([2]), array([3])]
podzielone

[array([1]), array([2]), array([3])]

## 4. Zaawansowane funkcje

### 4.1. Maski logiczne

In [32]:
a = np.array([1, 2, 3, 4, 5])
maska = a > 2
maska

array([False, False,  True,  True,  True])

In [33]:
wynik = a[maska]  # [3, 4, 5]
wynik

array([3, 4, 5])

### 4.2. Algebra liniowa

- **Iloczyn macierzy:**

In [35]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

iloczyn = np.dot(A, B)
iloczyn

array([[19, 22],
       [43, 50]])

- **Wyznacznik macierzy:**

In [36]:
wyznacznik = np.linalg.det(A)
wyznacznik

-2.0000000000000004

- **Rozwiązywanie układów równań:**

In [37]:
b = np.array([1, 2])
x = np.linalg.solve(A, b)

### 4.3. Funkcje statystyczne

In [38]:
a = np.array([1, 2, 3, 4, 5])

średnia = np.mean(a)
mediana = np.median(a)
odchylenie_standardowe = np.std(a)

średnia, mediana, odchylenie_standardowe

(3.0, 3.0, 1.4142135623730951)

## 5. Zastosowania NumPy

NumPy jest szeroko stosowany w dziedzinach takich jak:

- **Analiza danych:** Podstawa dla bibliotek takich jak Pandas.
- **Uczenie maszynowe:** Wykorzystywany w bibliotekach takich jak TensorFlow czy PyTorch.
- **Przetwarzanie obrazów:** Używany w bibliotekach takich jak OpenCV.
- **Obliczenia naukowe:** W połączeniu z SciPy umożliwia zaawansowane obliczenia numeryczne.